spring:
    application:
        name: z-dummy-api-alpha-server
    cloud:
        config:
            uri: http://localhost:9090


server:
    port: 2222

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
        healthcheck:
                  enabled: true
