server:
    port: 7777

spring.cloud.config.server.git.uri: https://github.com/supersun/backbone-microservice-demo.git


eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/





logging:
  level:
    root: WARN
    net.supersun: INFO

    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
    org.apache.catalina.session.ManagerBase: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO