spring:
    application:
        name: z-dummy-api-beta-server
    cloud:
        config:
            uri: http://localhost:9090


server:
    port: 3333

eureka:
    client:
        serviceUrl:
             defaultZone: http://localhost:8761/eureka/
        healthcheck:
                  enabled: true
